// Code generated by protoc-gen-go. DO NOT EDIT.
// source: data.proto

package main

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type PlayersTable struct {
	Id                   int32    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	PlayerName           string   `protobuf:"bytes,2,opt,name=player_name,json=playerName,proto3" json:"player_name,omitempty"`
	Online               string   `protobuf:"bytes,3,opt,name=online,proto3" json:"online,omitempty"`
	Address              string   `protobuf:"bytes,4,opt,name=address,proto3" json:"address,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PlayersTable) Reset()         { *m = PlayersTable{} }
func (m *PlayersTable) String() string { return proto.CompactTextString(m) }
func (*PlayersTable) ProtoMessage()    {}
func (*PlayersTable) Descriptor() ([]byte, []int) {
	return fileDescriptor_data_cb639e6a0920cf42, []int{0}
}
func (m *PlayersTable) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PlayersTable.Unmarshal(m, b)
}
func (m *PlayersTable) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PlayersTable.Marshal(b, m, deterministic)
}
func (dst *PlayersTable) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PlayersTable.Merge(dst, src)
}
func (m *PlayersTable) XXX_Size() int {
	return xxx_messageInfo_PlayersTable.Size(m)
}
func (m *PlayersTable) XXX_DiscardUnknown() {
	xxx_messageInfo_PlayersTable.DiscardUnknown(m)
}

var xxx_messageInfo_PlayersTable proto.InternalMessageInfo

func (m *PlayersTable) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *PlayersTable) GetPlayerName() string {
	if m != nil {
		return m.PlayerName
	}
	return ""
}

func (m *PlayersTable) GetOnline() string {
	if m != nil {
		return m.Online
	}
	return ""
}

func (m *PlayersTable) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func init() {
	proto.RegisterType((*PlayersTable)(nil), "josephusmv.redisql.PlayersTable")
}

func init() { proto.RegisterFile("data.proto", fileDescriptor_data_cb639e6a0920cf42) }

var fileDescriptor_data_cb639e6a0920cf42 = []byte{
	// 156 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xe2, 0xe2, 0x4a, 0x49, 0x2c, 0x49,
	0xd4, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x12, 0xca, 0xca, 0x2f, 0x4e, 0x2d, 0xc8, 0x28, 0x2d,
	0xce, 0x2d, 0xd3, 0x2b, 0x4a, 0x4d, 0xc9, 0x2c, 0x2e, 0xcc, 0x51, 0x2a, 0xe4, 0xe2, 0x09, 0xc8,
	0x49, 0xac, 0x4c, 0x2d, 0x2a, 0x0e, 0x49, 0x4c, 0xca, 0x49, 0x15, 0xe2, 0xe3, 0x62, 0xca, 0x4c,
	0x91, 0x60, 0x54, 0x60, 0xd4, 0x60, 0x0d, 0x02, 0xb2, 0x84, 0xe4, 0xb9, 0xb8, 0x0b, 0xc0, 0xf2,
	0xf1, 0x79, 0x89, 0xb9, 0xa9, 0x12, 0x4c, 0x40, 0x09, 0xce, 0x20, 0x2e, 0x88, 0x90, 0x1f, 0x50,
	0x44, 0x48, 0x8c, 0x8b, 0x2d, 0x3f, 0x2f, 0x27, 0x33, 0x2f, 0x55, 0x82, 0x19, 0x2c, 0x07, 0xe5,
	0x09, 0x49, 0x70, 0xb1, 0x27, 0xa6, 0xa4, 0x14, 0xa5, 0x16, 0x17, 0x4b, 0xb0, 0x80, 0x25, 0x60,
	0x5c, 0x27, 0xb6, 0x28, 0x96, 0xdc, 0xc4, 0xcc, 0xbc, 0x24, 0x36, 0xb0, 0xab, 0x8c, 0x01, 0x01,
	0x00, 0x00, 0xff, 0xff, 0x21, 0xca, 0x50, 0x16, 0xa3, 0x00, 0x00, 0x00,
}
