// Code generated by protoc-gen-go. DO NOT EDIT.
// source: strmrpc.proto

package main

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import timestamp "github.com/golang/protobuf/ptypes/timestamp"
import wrappers "github.com/golang/protobuf/ptypes/wrappers"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type StreamData struct {
	ID                   int64                `protobuf:"varint,1,opt,name=ID" json:"ID,omitempty"`
	Values               []string             `protobuf:"bytes,2,rep,name=Values" json:"Values,omitempty"`
	TimeStamp            *timestamp.Timestamp `protobuf:"bytes,3,opt,name=TimeStamp" json:"TimeStamp,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *StreamData) Reset()         { *m = StreamData{} }
func (m *StreamData) String() string { return proto.CompactTextString(m) }
func (*StreamData) ProtoMessage()    {}
func (*StreamData) Descriptor() ([]byte, []int) {
	return fileDescriptor_strmrpc_a2513a27b64e2274, []int{0}
}
func (m *StreamData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StreamData.Unmarshal(m, b)
}
func (m *StreamData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StreamData.Marshal(b, m, deterministic)
}
func (dst *StreamData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StreamData.Merge(dst, src)
}
func (m *StreamData) XXX_Size() int {
	return xxx_messageInfo_StreamData.Size(m)
}
func (m *StreamData) XXX_DiscardUnknown() {
	xxx_messageInfo_StreamData.DiscardUnknown(m)
}

var xxx_messageInfo_StreamData proto.InternalMessageInfo

func (m *StreamData) GetID() int64 {
	if m != nil {
		return m.ID
	}
	return 0
}

func (m *StreamData) GetValues() []string {
	if m != nil {
		return m.Values
	}
	return nil
}

func (m *StreamData) GetTimeStamp() *timestamp.Timestamp {
	if m != nil {
		return m.TimeStamp
	}
	return nil
}

func init() {
	proto.RegisterType((*StreamData)(nil), "gorpctutor.genfile.StreamData")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for Demostream service

type DemostreamClient interface {
	EnvoyerStream(ctx context.Context, opts ...grpc.CallOption) (Demostream_EnvoyerStreamClient, error)
}

type demostreamClient struct {
	cc *grpc.ClientConn
}

func NewDemostreamClient(cc *grpc.ClientConn) DemostreamClient {
	return &demostreamClient{cc}
}

func (c *demostreamClient) EnvoyerStream(ctx context.Context, opts ...grpc.CallOption) (Demostream_EnvoyerStreamClient, error) {
	stream, err := grpc.NewClientStream(ctx, &_Demostream_serviceDesc.Streams[0], c.cc, "/gorpctutor.genfile.demostream/EnvoyerStream", opts...)
	if err != nil {
		return nil, err
	}
	x := &demostreamEnvoyerStreamClient{stream}
	return x, nil
}

type Demostream_EnvoyerStreamClient interface {
	Send(*StreamData) error
	CloseAndRecv() (*wrappers.Int64Value, error)
	grpc.ClientStream
}

type demostreamEnvoyerStreamClient struct {
	grpc.ClientStream
}

func (x *demostreamEnvoyerStreamClient) Send(m *StreamData) error {
	return x.ClientStream.SendMsg(m)
}

func (x *demostreamEnvoyerStreamClient) CloseAndRecv() (*wrappers.Int64Value, error) {
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	m := new(wrappers.Int64Value)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// Server API for Demostream service

type DemostreamServer interface {
	EnvoyerStream(Demostream_EnvoyerStreamServer) error
}

func RegisterDemostreamServer(s *grpc.Server, srv DemostreamServer) {
	s.RegisterService(&_Demostream_serviceDesc, srv)
}

func _Demostream_EnvoyerStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(DemostreamServer).EnvoyerStream(&demostreamEnvoyerStreamServer{stream})
}

type Demostream_EnvoyerStreamServer interface {
	SendAndClose(*wrappers.Int64Value) error
	Recv() (*StreamData, error)
	grpc.ServerStream
}

type demostreamEnvoyerStreamServer struct {
	grpc.ServerStream
}

func (x *demostreamEnvoyerStreamServer) SendAndClose(m *wrappers.Int64Value) error {
	return x.ServerStream.SendMsg(m)
}

func (x *demostreamEnvoyerStreamServer) Recv() (*StreamData, error) {
	m := new(StreamData)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

var _Demostream_serviceDesc = grpc.ServiceDesc{
	ServiceName: "gorpctutor.genfile.demostream",
	HandlerType: (*DemostreamServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "EnvoyerStream",
			Handler:       _Demostream_EnvoyerStream_Handler,
			ClientStreams: true,
		},
	},
	Metadata: "strmrpc.proto",
}

func init() { proto.RegisterFile("strmrpc.proto", fileDescriptor_strmrpc_a2513a27b64e2274) }

var fileDescriptor_strmrpc_a2513a27b64e2274 = []byte{
	// 244 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x8f, 0x3d, 0x4b, 0xc4, 0x40,
	0x10, 0x40, 0x4d, 0x22, 0x81, 0x5b, 0x39, 0x8b, 0x2d, 0x24, 0x44, 0x90, 0x70, 0x55, 0xb4, 0xd8,
	0xc0, 0x29, 0x62, 0x2d, 0xb1, 0x48, 0x27, 0xb9, 0xc3, 0xc2, 0x42, 0xd8, 0xc4, 0xb9, 0x75, 0x21,
	0xfb, 0xc1, 0xec, 0x44, 0xf1, 0xdf, 0x8b, 0x89, 0xc7, 0x15, 0x07, 0x96, 0x03, 0x6f, 0xe6, 0xbd,
	0x61, 0xcb, 0x40, 0x68, 0xd0, 0xf7, 0xc2, 0xa3, 0x23, 0xc7, 0xb9, 0x72, 0xe8, 0x7b, 0x1a, 0xc9,
	0xa1, 0x50, 0x60, 0x77, 0x7a, 0x80, 0xfc, 0x5a, 0x69, 0xfa, 0x18, 0x3b, 0xd1, 0x3b, 0x53, 0x29,
	0xe7, 0xd4, 0x00, 0xd5, 0x04, 0x77, 0xe3, 0xae, 0xfa, 0x42, 0xe9, 0x3d, 0x60, 0x98, 0xd7, 0xf3,
	0x9b, 0x7f, 0x50, 0xd2, 0x06, 0x02, 0x49, 0xe3, 0x67, 0x76, 0x65, 0x19, 0xdb, 0x10, 0x82, 0x34,
	0xb5, 0x24, 0xc9, 0xcf, 0x59, 0xdc, 0xd4, 0x59, 0x54, 0x44, 0x65, 0xd2, 0xc6, 0x4d, 0xcd, 0x2f,
	0x58, 0xfa, 0x22, 0x87, 0x11, 0x42, 0x16, 0x17, 0x49, 0xb9, 0x68, 0xff, 0x26, 0xfe, 0xc0, 0x16,
	0x5b, 0x6d, 0x60, 0xf3, 0x7b, 0x28, 0x4b, 0x8a, 0xa8, 0x3c, 0x5b, 0xe7, 0x62, 0x56, 0x89, 0xbd,
	0x4a, 0x6c, 0xf7, 0xaa, 0xf6, 0x00, 0xaf, 0xdf, 0x18, 0x7b, 0x07, 0xe3, 0xc2, 0xe4, 0xe4, 0xcf,
	0x6c, 0xf9, 0x64, 0x3f, 0xdd, 0x37, 0xe0, 0x1c, 0xc1, 0xaf, 0xc4, 0xf1, 0xeb, 0xe2, 0x10, 0x98,
	0x5f, 0x1e, 0x59, 0x1a, 0x4b, 0xf7, 0x77, 0x53, 0xd6, 0xea, 0xa4, 0x8c, 0x1e, 0xd3, 0xd7, 0x53,
	0x23, 0xb5, 0xed, 0xd2, 0x09, 0xb8, 0xfd, 0x09, 0x00, 0x00, 0xff, 0xff, 0x16, 0x72, 0x52, 0xfe,
	0x5a, 0x01, 0x00, 0x00,
}
